version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-203-49-58.compute-1.amazonaws.com
            database: d116kc8r247a5r
            user: hjbrbnjajpmadp
            password: dc8c5cbc76255648ec2d5e69b8f1c7dbd5fd2cf3a4188777fc749a401f370f1e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true